# render
render_item: [world, left_cam, right_cam, ground_truth, esitimated]
render_x: 512
render_y: 512
sensor_x: 256
sensor_y: 64
cam:
  world_cam:
    width: null
    height: null
    crop: [1,1]
    camTargetPos: [0, 0, 0.1]
    camDistance: 0.12
    upAxisIndex: 2
    yaw: 90
    pitch: -10
    roll: 0
    fov: 90
    nearPlane: 0.01
    farPlane: 100
  left_cam:
    width: null
    height: null
    crop: [1,1]
    camTargetPos: null 
    camDistance: null 
    nearPlane: null
    farPlane: null
    upAxisIndex: 2
    yaw: 0
    pitch: 0
    roll: 0
    fov: 90
  right_cam:
    width: null
    height: null
    crop: [1,1]
    camTargetPos: null
    camDistance: null
    nearPlane: null
    farPlane: null
    upAxisIndex: 2
    yaw: 180
    pitch: 0
    roll: 0
    fov: 90

# depth sensor setting
sensor_near: 0.001
sensor_far: 0.08
# camera distance to the object surface
depth_cam_min_distance: 0.03

# assets
obj_urdf: /juno/u/chaoyi/rl/roller_grasper_tacto/assets/objects/curved_cube.urdf
obj_pos: [0.000, 0, 0.13]
obj_copy_pos: [0.0, 0.15, 0.13]
obj_target_pos: [0.0, -0.15, 0.13]
robot_params:
  urdf_path: /juno/u/chaoyi/rl/roller_grasper_tacto/assets/robots/roller.urdf
  use_fixed_base: True
  base_position: [0, 0, 0.3]
init_state:
  wrist_angle: 0
  finger_l: -0.008
  finger_r: +0.008
  pitch_l_angle: 0
  pitch_r_angle: 0
  roll_l_angle: 0
  roll_r_angle: 0

# SLAM
matching_num: 5
voxel_size: 0.00002
fit_bar: 0.01  # fitness bar to conduct graph optimization
start_detect_loop_idx: 38
detect_loop_extend: 15
use_pcd_goal: False

# simulation
total_steps: 2
file_prefix: debug